package:
  name: zlib
  version: 1.2.11
  epoch: 1
  description: "zlib library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Zlib
  dependencies:
    runtime:

# The secfixes section is used to generate a VEX feed for
# scanners to consume.
secfixes:
  '1.2.11-r1':
     - CVE-2018-25032

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/zlib-patch-demo
  - uses: fetch
    with:
      uri: https://zlib.net/fossils/${{package.name}}-${{package.version}}.tar.gz
      expected-sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
  - uses: patch
    with:
      patches: CVE-2018-25032.patch
  - runs: |
      ./configure --prefix=/usr --libdir=/lib --shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
