name: Build action

on: push

jobs:
  build:
    name: Build zlib package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
